import {
  createResource,
  createSignal,
  For,
  onCleanup,
  onMount,
  Show,
  createEffect,
} from "solid-js";
import { Portal } from "solid-js/web";
import { fetchSessions, renameSession, deleteSession } from "../lib/sessions";
import { sessionManager } from "../lib/sessionManager";
import { sessionActivity } from "../lib/anp/orchestrator";
import StealthButton from "./StealthButton";
import Modal from "./Modal";
import ScrollArea from "./ScrollArea";

interface SidebarProps {
  isCollapsed: boolean;
  onToggle: () => void;
}

export default function Sidebar(props: SidebarProps) {
  const [sessions, { refetch, mutate }] = createResource(() => fetchSessions());
  const [openMenuId, setOpenMenuId] = createSignal<string | null>(null);
  const [menuPosition, setMenuPosition] = createSignal<{
    top: number;
    left: number;
  } | null>(null);
  const [deleteModalOpen, setDeleteModalOpen] = createSignal(false);
  const [sessionToDelete, setSessionToDelete] = createSignal<string | null>(
    null
  );
  const [renameModalOpen, setRenameModalOpen] = createSignal(false);
  const [sessionToRename, setSessionToRename] = createSignal<{
    id: string;
    title: string;
  } | null>(null);
  const [newTitle, setNewTitle] = createSignal("");
  const currentSessionId = sessionManager.currentSessionId;

  const handleNewChat = () => {
    // Clear the chat view by switching to "new session" state
    // The actual session ID will be generated by the backend when the first message is sent
    sessionManager.clearSession();
  };

  const handleRename = (sessionId: string, currentTitle: string) => {
    setOpenMenuId(null);
    setMenuPosition(null);
    setSessionToRename({ id: sessionId, title: currentTitle });
    setNewTitle(currentTitle);
    setRenameModalOpen(true);
  };

  const confirmRename = async () => {
    const session = sessionToRename();
    const title = newTitle().trim();
    if (!session || !title || title === session.title) return;

    setRenameModalOpen(false);
    setSessionToRename(null);
    setNewTitle("");

    try {
      await renameSession(session.id, title);
      refetch();
    } catch (error) {
      alert(`Failed to rename session: ${error}`);
    }
  };

  const cancelRename = () => {
    setRenameModalOpen(false);
    setSessionToRename(null);
    setNewTitle("");
  };

  const handleDelete = async (sessionId: string) => {
    setOpenMenuId(null);
    setMenuPosition(null);
    setSessionToDelete(sessionId);
    setDeleteModalOpen(true);
  };

  const confirmDelete = async () => {
    const sessionId = sessionToDelete();
    if (!sessionId) return;

    setDeleteModalOpen(false);
    setSessionToDelete(null);

    const currentSessions = sessions();
    if (!currentSessions) return;

    try {
      // Perform the backend deletion
      await deleteSession(sessionId);

      // If we deleted the currently active session, switch to new session
      if (currentSessionId() === sessionId) {
        sessionManager.clearSession();
      }

      // Remove from the UI optimistically
      const updatedSessions = currentSessions.filter((s) => s.id !== sessionId);
      mutate(updatedSessions);
    } catch (error) {
      console.error("Delete failed", error);
      alert(`Failed to delete session: ${error}`);
      // Rollback on failure
      refetch();
    }
  };

  const cancelDelete = () => {
    setDeleteModalOpen(false);
    setSessionToDelete(null);
  };

  // Watch for new sessions created via currentSessionId
  let previousSessionId: string | null = null;
  createEffect(() => {
    const sessionId = currentSessionId();
    const currentSessions = sessions();

    // If session changed from null to a value, it's a new session
    if (sessionId && !previousSessionId && currentSessions) {
      // Check if it's already in the list
      const exists = currentSessions.some((s) => s.id === sessionId);
      if (!exists) {
        // Optimistically add the new session to the list
        // Use pending title (first line of user message) if available, otherwise "New Chat"
        const pendingTitle = sessionManager.pendingSessionTitle();
        const newSession = {
          id: sessionId,
          title: pendingTitle || "New Chat",
          updated_at: new Date().toISOString(),
        };
        // Prepend to show it at the top (most recent)
        const updatedSessions = [newSession, ...currentSessions];
        mutate(updatedSessions);
      }
    }
    previousSessionId = sessionId;
  });

  // Function to reorder a session to the top (for any session activity)
  const reorderSessionToTop = (sessionId: string) => {
    const currentSessions = sessions();
    if (!currentSessions) return;

    const index = currentSessions.findIndex((s) => s.id === sessionId);
    // If session is not found or already at the top, do nothing to avoid
    // redundant mutations that can trigger reactive loops
    if (index <= 0) return;

    const session = currentSessions[index];
    const otherSessions = currentSessions.filter((s) => s.id !== sessionId);
    const reorderedSessions = [session, ...otherSessions];
    mutate(reorderedSessions);
  };

  // Reorder sessions when ANP notifications indicate agent activity
  createEffect(() => {
    const activeSessionId = sessionActivity.sessionActivity();
    if (activeSessionId) {
      reorderSessionToTop(activeSessionId);
    }
  });

  // Close menu when clicking outside
  onMount(() => {
    const handleClickOutside = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      if (
        !target.closest("[data-menu-container]") &&
        !target.closest("[data-menu-dropdown]")
      ) {
        setOpenMenuId(null);
        setMenuPosition(null);
      }
    };
    document.addEventListener("click", handleClickOutside);
    onCleanup(() => document.removeEventListener("click", handleClickOutside));
  });

  // Static padding to center icons in collapsed sidebar (64px)
  // Icon width: 20px (w-5 = 1.25rem)
  // Padding = (64 - 20) / 2 = 22px
  const COLLAPSED_WIDTH = 64;
  const ICON_WIDTH = 20; // w-5 = 1.25rem = 20px
  const staticPadding = `${(COLLAPSED_WIDTH - ICON_WIDTH) / 2}px`;

  return (
    <div class="h-full flex flex-col min-h-0 relative overflow-hidden select-none">
      {/* Fixed button bar - always in same position and height */}
      <div
        class="border-b border-[var(--border-secondary)] flex flex-col gap-3 h-[120px] py-4"
        style={{
          "padding-left": staticPadding,
          "padding-right": staticPadding,
        }}
      >
        <StealthButton
          onClick={props.onToggle}
          class="self-start h-[36px] flex items-center justify-center"
          title={props.isCollapsed ? "Expand sidebar" : "Collapse sidebar"}
        >
          <Show
            when={props.isCollapsed}
            fallback={
              <svg
                class="w-5 h-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path d="M15 19l-7-7 7-7" />
              </svg>
            }
          >
            <svg
              class="w-5 h-5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M9 5l7 7-7 7"
              />
            </svg>
          </Show>
        </StealthButton>
        <StealthButton
          onClick={handleNewChat}
          class="flex items-center gap-2 self-start h-[36px]"
          title="New chat"
        >
          <svg
            class="w-5 h-5 flex-shrink-0"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 4v16m8-8H4"
            />
          </svg>
          <span
            class="text-white text-sm font-mono transition-opacity duration-300 truncate w-[120px]"
            classList={{
              "opacity-0": props.isCollapsed,
              "opacity-100": !props.isCollapsed,
            }}
          >
            New chat
          </span>
        </StealthButton>
      </div>

      {/* Expanded content - faded when collapsed */}
      <div
        class={`flex-1 flex flex-col min-h-0 transition-opacity duration-300 w-[280px] ${
          props.isCollapsed ? "opacity-0 pointer-events-none" : "opacity-100"
        }`}
      >
        <ScrollArea class="flex-1">
          <Show
            when={!sessions.loading}
            fallback={
              <div class="p-4 text-zinc-500 text-sm">Loading sessions...</div>
            }
          >
            <Show
              when={sessions() && sessions()!.length > 0}
              fallback={
                <div class="p-4 text-zinc-500 text-sm">No sessions yet</div>
              }
            >
              <For each={sessions()}>
                {(session) => {
                  const isActive = () => {
                    const currentId = currentSessionId();
                    // Session is active if currentId matches session.id and is not null
                    return currentId === session.id && currentId !== null;
                  };
                  return (
                    <div class="group relative">
                      <div
                        onClick={() => {
                          sessionManager.loadSession(session.id);
                        }}
                        class={`flex items-center w-full hover:bg-[var(--bg-tertiary)] transition-colors px-4 py-3 ${
                          isActive()
                            ? "bg-[var(--bg-tertiary)] border-l-2 border-l-[var(--color-primary)]"
                            : ""
                        }`}
                      >
                        <div class="text-sm text-zinc-100 truncate whitespace-nowrap max-w-[240px] group-hover:max-w-[calc(100%)] flex-1 text-left min-w-0 overflow-hidden">
                          {session.title || "New Chat"}
                        </div>
                        <div
                          class="relative flex-shrink-0 flex items-center justify-center transition-all z-10"
                          classList={{
                            "w-0 overflow-hidden opacity-0 group-hover:w-auto group-hover:opacity-100":
                              openMenuId() !== session.id,
                            "w-auto opacity-100": openMenuId() === session.id,
                          }}
                          data-menu-container
                        >
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              const button = e.currentTarget;
                              const rect = button.getBoundingClientRect();
                              if (openMenuId() === session.id) {
                                setOpenMenuId(null);
                                setMenuPosition(null);
                              } else {
                                setOpenMenuId(session.id);
                                // Center dropdown on button: button center - dropdown half width
                                // Dropdown width is 192px (w-48 = 12rem)
                                const dropdownWidth = 192;
                                const buttonCenter = rect.left + rect.width / 2;
                                setMenuPosition({
                                  top: rect.bottom + 4,
                                  left: buttonCenter - dropdownWidth / 2,
                                });
                              }
                            }}
                            class="p-0 text-zinc-400 hover:text-zinc-100 transition-colors relative z-10 cursor-pointer"
                            title="Session options"
                          >
                            <svg
                              class="w-5 h-5"
                              fill="none"
                              stroke="currentColor"
                              viewBox="0 0 24 24"
                            >
                              <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z"
                              />
                            </svg>
                          </button>
                        </div>
                      </div>
                    </div>
                  );
                }}
              </For>
            </Show>
          </Show>
        </ScrollArea>
      </div>
      {/* Dropdown menu - rendered via portal to avoid overflow clipping */}
      <Portal>
        <Show when={openMenuId() && menuPosition()}>
          <div
            data-menu-dropdown
            class="fixed z-[100] w-48 bg-[var(--bg-tertiary)] border border-[var(--border-primary)] rounded-md"
            style={{
              top: `${menuPosition()!.top}px`,
              left: `${menuPosition()!.left}px`,
            }}
          >
            <button
              onClick={(e) => {
                e.stopPropagation();
                const sessionId = openMenuId();
                if (sessionId) {
                  const session = sessions()?.find((s) => s.id === sessionId);
                  if (session) {
                    handleRename(sessionId, session.title || "New Chat");
                  }
                }
              }}
              class="w-full px-4 py-2 text-left text-sm text-zinc-100 hover:bg-zinc-700 transition-colors first:rounded-t-md"
            >
              Rename
            </button>
            <button
              onClick={(e) => {
                e.stopPropagation();
                const sessionId = openMenuId();
                if (sessionId) {
                  handleDelete(sessionId);
                }
              }}
              class="w-full px-4 py-2 text-left text-sm text-red-400 hover:bg-zinc-700 transition-colors last:rounded-b-md"
            >
              Delete
            </button>
          </div>
        </Show>
      </Portal>

      <Modal
        isOpen={deleteModalOpen()}
        onClose={cancelDelete}
        title="Delete Session"
        actions={
          <>
            <button
              onClick={cancelDelete}
              class="px-4 py-2 text-sm text-zinc-300 hover:text-zinc-100 transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              onClick={confirmDelete}
              class="px-4 py-2 text-sm bg-red-600 text-white hover:bg-red-700 transition-colors rounded cursor-pointer"
            >
              Delete
            </button>
          </>
        }
      >
        <p class="text-zinc-300 text-sm">
          Are you sure you want to delete this session? This action cannot be
          undone.
        </p>
      </Modal>

      <Modal
        isOpen={renameModalOpen()}
        onClose={cancelRename}
        title="Rename Session"
        actions={
          <>
            <button
              onClick={cancelRename}
              class="px-4 py-2 text-sm text-zinc-300 hover:text-zinc-100 transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              onClick={confirmRename}
              class="px-4 py-2 text-sm font-bold bg-[var(--color-primary)] hover:bg-[var(--color-primary-highlight)] text-black transition-colors rounded cursor-pointer"
              disabled={
                !newTitle().trim() ||
                newTitle().trim() === sessionToRename()?.title
              }
            >
              Rename
            </button>
          </>
        }
      >
        <div class="space-y-4">
          <input
            type="text"
            value={newTitle()}
            onInput={(e) => setNewTitle(e.currentTarget.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                confirmRename();
              }
            }}
            class="w-full px-3 py-2 bg-[var(--bg-secondary)] border border-[var(--border-primary)] rounded-md text-zinc-100 placeholder-zinc-500 focus:outline-none"
            placeholder="Enter new session name"
            autofocus
          />
        </div>
      </Modal>
    </div>
  );
}
